// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    
		int N = Integer.parseInt(args[0]);

		int belowHalf = 0;
		int aboveHalf = 0;
		int counter = 0;

		while( counter < N) {

			if(Math.random() > 0.5){
				aboveHalf++;
			}
			else{
				belowHalf++;
			}
			counter++;
		}

		System.out.println("> 0.5: " + aboveHalf + " times");
		System.out.println("<= 0.5: " + belowHalf + " times");

		double newAbove = (double)(aboveHalf);
		double newBelow = (double)(belowHalf);

		if(aboveHalf != 0 && belowHalf != 0){

			System.out.println("Ratio:" + newAbove / newBelow);
		}
		

	}
}
